site_name: JDA-Wiki
site_description: 'Wiki about JDA'
site_author: 'Andre_601'

docs_dir: docs/

repo_name: 'DV8FromTheWorld/JDA'
repo_url: 'https://github.com/DV8FromTheWorld/JDA/'
edit_uri: 'https://github.com/Andre601/JDA-Wiki/edit/master/docs'

nav:
  - Welcome: index.md
  - Setup:
    - Setup: setup/index.md
    - IntelliJ: setup/intellij.md
    - Eclipse: setup/eclipse.md
    - Netbeans: setup/netbeans.md
  - Use:
    - Getting started: usage/index.md
    - RestAction: usage/restaction.md
    - GatewayIntents: usage/gatewayintents.md

theme:
  name: 'material'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  features:
  - tabs

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/DV8FromTheWorld/JDA'

extra_css:
- 'assets/css/dark.css'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
